Responses/urls.py
from django.urls import path
from . import views
from Responses import views

app_name = 'Responses'

urlpatterns = [
    # Untuk forms
    path('review/', views.emp, name='review'),  
    path('feedback/',views.show, name='feedback'),    
    path('delete/<int:id>', views.destroy),
    
]

Testimoni/urls.py
from django.contrib import admin
from django.urls import path, include
from Responses import views  
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Responses.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('balasan/', views.replytesti, name='balasan'),
]

nunun/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from . import views

# Create your views here.
app_name = 'nunun'

urlpatterns = [
	path('create', view.input)
	path('', view.output, name='output')
]

story/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

Responses/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Responses(models.Model):   
    ename = models.CharField(max_length=20)
    eemail = models.EmailField()
    ereview = models.CharField(max_length=160)
    erating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    class Meta:  
        db_table = "responses"  

homepage/models.py
from django.db import models

# Create your models here.
class ReplyTesti(models.Model):
    name = models.CharField(max_length=100, default='')
    email = models.CharField(max_length=100)
    balasan = models.TextField(max_length=1000)

nunun/models.py
from django.db import models

# Create your models here.
class Input(models.Model):
	nama = models.CharField(max_length=50)
    no_telp = models.CharField(max_length=25)
    alamat = models.CharField(max_length=50)

    def __str__(self):
        return self.nama

Responses/forms.py
from django import forms  
from Responses.models import Responses
class ResponsesForm(forms.ModelForm):  
    class Meta:  
        model = Responses 
        fields = "__all__"

homepage/forms.py
from.models import ReplyTesti
from django import forms

class ReplyTestiForm(forms.ModelForm):
    class Meta:
        model = ReplyTesti
        fields = ['name', 'email', 'balasan']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

nunun/forms.py
from django.shortcuts import render
from . import models
from django import forms

# Create your views here.
class InputForm(forms.ModelForm):
	nama = forms.CharFieldwidget(widget=forms.TextInput(attrs={
        "class" : "jadwalfields full",
        "required" : True,
        "placeholder":"Nama Kegiatan",
        }))
	no_telp = forms.CharFieldwidget(widget=forms.TextInput(attrs={
        "class" : "jadwalfields full",
        "required" : True,
        "placeholder":"Nama Kegiatan",
        }))
	alamat = forms.CharFieldwidget(widget=forms.TextInput(attrs={
        "class" : "jadwalfields full",
        "required" : True,
        "placeholder":"Nama Kegiatan",
        }))

	class Meta:
		model = models.Input
		fields = ["nama", "no_telp", "alamat"]

Responses/views.py
from django.shortcuts import render, redirect  
from Responses.forms import ResponsesForm  
from Responses.models import Responses

# TestCase
from django.views.generic import TemplateView

# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = ResponsesForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/review/')  
            except:  
                pass  
    else:  
        form = ResponsesForm()  
    return render(request,'review.html',{'form':form})  
def show(request):  
    responses = Responses.objects.all()  
    return render(request,"feedback.html",{'responses':responses})   
def destroy(request, id):  
    response = Responses.objects.get(id=id)  
    response.delete()  
    return redirect("/review/")  

# For TestCase

class ReviewPageView(TemplateView):
    template_name = 'review.html'


class FeedbackPageView(TemplateView):
    template_name = 'feedback.html'

homepage/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def replytesti(request):
    return render(request, 'replyTesti.html')

nunun/views.py
from django.shortcuts import render

# Create your views here.
def input(request):
	form = InputForm()
    if request.method =="POST":
        form=inputForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('input:input')
    return render(request, 'inputPengiriman.html', {'form':form})

def output(request):
	output = Input.objects.order_by("nama")
    response = {
        'input' : output,
        }
	return render(request, 'outputPengiriman.html', response)

Responses/templates/feedback.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Bungkusaja - About Us</title>  
     {% load staticfiles %} 
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
</head>  
    
<body id="white-bg">
    
    <!-- Navigation Bar -->
    {% include 'navbar.html' %}
    
<div class="container " id="testi" style="margin-top: 100px; text-align: left">
    <h1>Testimoni</h1>
</div>
    <div class=middle-confirmed style="display: flex; justify-content: center;">
        <table class="table table-striped table-bordered table-sm" align="center" style="align-self: center; width: 75%;">  
            <thead class="thead-choco">   
                <tr>
                    <th>Reviewer</th>  
                    <th>E-mail</th>  
                    <th>Review</th>  
                    <th>Rating</th>  
                    <th>Action</th>  
                </tr>  
            </thead>  
            <tbody>  
                {% for responses in responses %}  
                <tr>  
                    <td>{{ responses.ename }}</td>  
                    <td>{{ responses.eemail }}</td>  
                    <td>{{ responses.ereview }}</td>
                    <td>{{ responses.erating }}</td> 
                    <td>  <a href="/delete/{{ responses.id }}">Delete</a>  </td>  
                </tr>  
            {% endfor %}  
            </tbody>  
        </table>  
    </div>
<br>  
<br>   
</body>  
</html>

Responses/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Bungkusaja - File-A-Review!</title>  
    {% load staticfiles %}  
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
    {% csrf_token %}  
    <div class="container">  
        <br>  
        <div class="form-group row">  
            <label class="col-sm-1 col-form-label"></label>  
            <div class="col-sm-4">  
                <h3>Enter Details</h3>  
            </div>  
        </div>  
        <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Employee Id:</label>  
            <div class="col-sm-4">  
                {{ form.eid }}  
            </div>  
        </div>  
        <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Employee Name:</label>  
            <div class="col-sm-4">  
                {{ form.ename }}  
            </div>  
        </div>  
        <div class="form-group row">  
            <label class="col-sm-2 col-form-label">Employee Contact:</label>  
            <div class="col-sm-4">  
                {{ form.ereview }}  
            </div>  
        </div>  
        <div class="form-group row">  
            <label class="col-sm-1 col-form-label"></label>  
            <div class="col-sm-4">  
                <button type="submit" class="btn btn-primary">Submit</button>  
            </div>  
        </div>  
    </div>  
</form>  
</body>  
</html>

Responses/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
    
<body id="navbar">
    
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-customgrey fixed-top">
    <div class="container">
        <a class="navbar-brand-custom" href=""><img src="{% static 'images/logo.png' %}" height="25vh"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href=""><b>Home</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Responses:review' %}"><b>Review</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=""><b>Mitra</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Responses:feedback' %}"><b>Feedback</b></a>
                </li>
            </ul>
        </div>
    </div>
    </nav>
    
    {% block content %}
    {% endblock content %}
    </body>
</html>

<script>
    window.addEventListener('scroll', () => {
   let children = parent.getElementsByTagName('div');
   for(let i = 0; i < children.length; i++) {
     children[i].style.transform = 'translateY(-' + (window.pageYOffset * i / children.length) + 'px)';
   }
}, false)</script>

Responses/templates/review.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="let USER to write reviews regarding their experiences using BUNGKUSAJA">
    <meta name="author" content="made by Muhammad Zakiy Saputra">
    
    <title>bungkusaja - Fill a Review</title>  

    <!-- Bootstrap core CSS, semi-edited by Zakiy -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
</head>
    
<body id="white-bg">
    
    <!-- Navigation Bar -->
    {% include 'navbar.html' %}
    
    {% block content %}
    <form method="POST" class="post-form" action="/review/">  
    {% csrf_token %}
    <center>
    <div class="container" id="middle-assurance">  
        <br>  
        <div class="form-group row" style="display: flex; justify-content: center;">  
            <label class="col-sm-1 col-form-label"></label>  
            <div class="col-sm-4">  
                <h3>Testimoni</h3>  
            </div>  
        </div>  
        <div class="form-group row" style="display: flex; justify-content: center;">  
            <label class="col-sm-2 col-form-label">Name:</label>  
            <div class="col-sm-4">  
                {{ form.ename }}  
            </div>  
        </div>  
        <div class="form-group row" style="display: flex; justify-content: center;">  
            <label class="col-sm-2 col-form-label">Email:</label>  
            <div class="col-sm-4">  
                {{ form.eemail }}  
            </div>  
        </div>  
        <div class="form-group row" style="display: flex; justify-content: center;">  
            <label class="col-sm-2 col-form-label">Review:</label>  
            <div class="col-sm-4">  
                {{ form.ereview }}  
            </div>  
        </div>  
        <div class="form-group row" style="display: flex; justify-content: center;">  
            <label class="col-sm-2 col-form-label">Rating:</label>  
            <div class="col-sm-4">  
                {{ form.erating }}  
            </div>  
        </div>
        <div class="form-group row" style="display: flex; justify-content: center;">  
            <label class="col-sm-1 col-form-label"></label>  
            <div class="col-sm-4">  
                <button type="submit" class="btn btn-primary">Kirim</button>  
            </div>  
        </div>
    </div>  
    </center>
</form>
    {% endblock content %}
</body>  
</html>

Responses/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Bungkusaja - About Us</title>  
     {% load staticfiles %} 
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for responses in responses %}  
    <tr>  
        <td>{{ responses.eid }}</td>  
        <td>{{ responses.ename }}</td>  
        <td>{{ responses.ereview }}</td> 
        <td>  
            <a href="/delete/{{ responses.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>

homepage/templates/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>bungkusaja</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bungkus.css' %}" rel="stylesheet">

</head>

<body style="background-color: #DBAC83;">
  <nav class="sticky-top top_navigation">
      <a><img src="{% static 'images/logo.png' %}" height="25vh"></a>
      <a href="#home">home</a>
      <a href="#feedback">feedback</a>
      <a style="float:right" class="active" href="#mitra">mitra</a>
    </nav>

    <div class="jumbotron" style="background: transparent">
      <div class="container-fluid">
  
        <div class="row flex-container">
          <div class="col-sm-4 m-auto"></div>
  
          <div class="col-sm-4 flex-container mx-auto d-block" >
            <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="Responsive image" style="position: center">
          </div>
  
          <div class="col-sm-4 m-auto"></div>
        </div>

        <br>
        <br>
        <br>
        
        <div class="row flex-container">
          <div class="col-sm-5 m-auto"></div>
  
          <div class="col-sm-2 m-auto" style="text-align: center">
            <a href="buat.html"><img src="{% static 'images/BUATBuatButton.png' %}" class="img-fluid" alt="Responsive image"></a>
          </div>
          
          <div class="col-sm-5 m-auto"></div>
        </div>
  
      </div>
    </div>
</body>
</html>

homepage/templates/replyTesti.html
!DOCTYPE html>

{% load static %}

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>bungkusaja</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bungkus.css' %}" rel="stylesheet">

</head>

<body style="background-color: #DBAC83;">
  <nav class="sticky-top top_navigation">
      <a><img src="{% static 'images/logo.png' %}" height="25vh"></a>
      <a href="#home">home</a>
      <a href="#feedback">feedback</a>
      <a style="float:right" class="active" href="#mitra">mitra</a>
    </nav>

    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            {% for fields in form %}
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-1"></div>
        <input type="submit" class="btn btn-primary float-right" value="Add">
    </div>
</body>

nunun/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>bungkusaja</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bungkus.css' %}">
</head>

<body style="background-color: #DBAC83;">
    <nav class="sticky-top top_navigation">
        <a><img src="logo.png" height="25vh"></a>
        <a href="#home">home</a>
        <a href="#feedback">feedback</a>
        <a style="float:right" class="active" href="#mitra">mitra</a>
      </nav>

      <div class="jumbotron" style="background: transparent">
        <div class="container-fluid">
    
          <div class="row flex-container">
            <div class="col-sm-4 m-auto"></div>
    
            <div class="col-sm-4 flex-container mx-auto d-block" >
              <img src="logo.png" class="img-fluid" alt="Responsive image" style="position: center">
            </div>
    
            <div class="col-sm-4 m-auto"></div>
          </div>

          <br>
          <br>
          <br>
          
          <div class="row flex-container">
            <div class="col-sm-5 m-auto"></div>
    
            <div class="col-sm-2 m-auto" style="text-align: center">
              <a href="buat.html"><img src="BUATBuatButton.png" class="img-fluid" alt="Responsive image"></a>
            </div>
            
            <div class="col-sm-5 m-auto"></div>
          </div>
    
        </div>
      </div>
      {% block content %}
      {% end block %}
</body>
</html>

nunun/templates/inputPengiriman.html
{% extends 'base.html' %}

<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Detail Pengiriman</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mystyles.css' %}">
</head>
<body>
	<!-- navbar -->
	<div class="col-7 padding">
		<div class="row justify-content-center">
			<p>Detail pengiriman</p>
		</div>
	</div>
	
	<form> <!-- need an action-->
		<div class="form-group row justify-content-center padding">
			<div class="col-1">
				<label for="exampleInputNama"> Nama </label>
			</div>
			<div class="col-4">
				<input class="form-control" type="text">
			</div>
		</div>
		<div class="form-group row justify-content-center">
			<div class="col-1">
				<label for="exampleInputNama"> No. Telp </label>
			</div>
			<div class="col-4">
				<input class="form-control" type="text">
			</div>
		</div>
		<div class="form-group row justify-content-center">
			<div class="col-1">
				<label for="exampleInputNama"> Alamat </label>
			</div>
			<div class="col-4">
				<input class="form-control panjang" type="text">
			</div>
		</div>
		<div class="row justify-content-center padding">
				<input type="submit" value="KONFIRMASI">
		</div>
	</form>
	{% block content %}
</body>
</html>

nunun/templates/outputPengiriman.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Detail Pengiriman</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mystyles.css' %}">
</head>
<body>
	<!-- navbar -->
	<div class="col-4 padding">
		<div class="row justify-content-center">
			<p>Detail pengiriman</p>
		</div>
	</div>
	<div class="container">
		<div class="row" style="background-color: #775433">
			<div class="col-sm">
				Nama
			</div>
			<div class="col-sm">
				No. Telp
			</div>
			<div class="col-sm">
				Alamat
			</div>
		</div>
		<div class="row form" style="background-color: #C4C4C4">
			<div class="col">
				isi Nama
			</div>
			<div class="col">
				isi No. Telp
			</div>
			<div class="col">
				isi Alamat
			</div>
		</div>
		<div class="row" style="background-color: #DBAC83">
			<div class="col">
			
			</div>
			<div class="col">
			Ongkir
			</div>
		</div>
	</div>
</body>
</html>